# The ID of the dataset you created above.
dataset: leave-out-some-fted-gpt35-2-jul
epochs: 1.0
batch_size: 16
learning_rate: 0.0001
wandb_entity: chuajamessh
wandb_project: fire
wandb_api_key: 111
model_id: llama-3-70b-on-fted-gpt35-2jul
conversation: {}
base_model: meta-llama/Meta-Llama-3-70B-Instruct
lora_rank: 16