hydra:
  run:
    dir: ${exp_dir}/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${exp_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job_logging:
    root:
      level: INFO

defaults:
  - language_model: gpt-3.5-turbo
  - prompt: property_extraction/minimal
  - response_property: sentiment

dir: ??? # path to the directory containing the object level responses.
exp_dir: ${dir}/property_extraction_${response_property.name}_${language_model.model}

# Model
language_model:
  temperature: 0.0
  logprobs: 5

logging: INFO
print_prompt_and_response: false
cache_dir: ${exp_dir}/cache
prompt_history_dir: ${exp_dir}/prompt_history

# API
organization: OWAIN_ORG
anthropic_tag: ANTHROPIC_API_KEY
openai_tag: OPENAI_API_KEY
anthropic_num_threads: 12
openai_fraction_rate_limit: 0.9
